# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# app/config/route/liip_imagine.yml

liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        produit_thumbnail: 
            quality: 75

            filters:
                fixed:
                    width: 100
                    height: 100

        produit_big:
            quality: 75

            filters:
                fixed:
                    width: 550
                    heigth: 750